<? 
$registry = Zend_Registry::getInstance();
$config = $registry->get(Pandamp_Keys::REGISTRY_APP_OBJECT);
$remoteSearchIn = $config->getOption('in');
$remoteSearchEn = $config->getOption('en');

if ($this->getLanguage() == "id") 
{ 
	$title = "Berita Terbaru";	
	
	
} else {
	$title = "Indonesian Legal News";
	
}	
?>
<h5><?=$title;?></h5>
<hr>
<div class="td_peraturan1">
    <div style="height:auto;">
        <ul id="navlistnoline">
            <? for($i=0; $i<$this->numberOfRows;$i++) { ?>
            <li><span class="judul">[<?=$this->data[$i][2]; ?>]</span>&nbsp;
            <? if ($this->getLanguage() == "id") {
    			$link = $remoteSearchIn['website']."/berita/baca/".$this->data[$i][3]."/".$this->data[$i][1];        
            } else { 
				if (isset($this->data[$i][1])) {
					$st = "/".$this->data[$i][1];	
				}
				else 
				{
					$st = "";
				}
				
				//$link = $remoteSearchEn['website']."/pages/".$this->data[$i][3].$st;
				$link = $remoteSearchEn['website']."/pages/".$this->data[$i][3];
            
            } ?>
            <a href="<?=$link;?>" title="<?=$this->data[$i][4]; ?>"><?=$this->data[$i][0]; ?></a></li>
            <? } ?>
        </ul>
    </div>
</div>