<div class="align-left">
<div style="padding-left:10px">
<a href="http://www.hukumonline.com">hukumonline.com</a>&nbsp;|&nbsp;<a href="http://en.hukumonline.com">en.hukumonline.com</a>&nbsp;|&nbsp;<a href="http://www.hukumpedia.com">hukumpedia.com</a>
</div>
</div>
<div class="align-right">
	<div style="padding-right:5px">
	<?if ($this->isLoggedIn) { ?>
	<h6><?=$this->username; ?> &nbsp;|&nbsp; <a href="#" onclick="window.location='<?=$this->profile;?>';return false;">Profile</a> &nbsp;|&nbsp; <a href="#" onclick="window.location='<?=$this->logoutUrl;?>';return false;">logout</a></h6>
	<? } else { ?>
	<h6><a href="#" onclick="window.location='<?=$this->signUp;?>';return false;">Daftar</a> &nbsp;|&nbsp; <a href="#" onclick="window.location='<?=$this->loginUrl;?>';return false;">Masuk</a></h6>
	<? } ?>
	</div>
</div>
<div style="clear:both;border-bottom:1px solid #c9d7f1;"></div>